# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('amount_paid', models.PositiveIntegerField()),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('national_id', models.PositiveIntegerField()),
                ('license', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_full_name', models.CharField(max_length=128)),
                ('sender_phone_no', models.CharField(max_length=13)),
                ('sender_national_id', models.PositiveIntegerField()),
                ('receiver_phone_no', models.CharField(max_length=13)),
                ('receiver_national_id', models.PositiveIntegerField()),
                ('parcel_description', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_type', models.CharField(choices=[('Parcel', 'Parcel'), ('Luggage', 'Luggage')], max_length=32)),
                ('parcel_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Parcel Fee (Ksh)')),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('national_id', models.PositiveIntegerField(blank=True)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=13)),
                ('payment_mode', models.CharField(max_length=20)),
                ('payment_for', models.CharField(choices=[('Fare', 'Fare'), ('Parcel', 'Parcel'), ('Other', 'Other')], default='Fare', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(max_length=32)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('fare', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Travelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128)),
                ('destination', models.CharField(max_length=128)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('available_capacity', models.PositiveIntegerField(default=0)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('vehicle_category', models.CharField(choices=[('14 Seater', '14 Seater'), ('Mini-Bus', 'Mini-Bus'), ('Bus', 'Bus')], max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('is_departed', models.BooleanField(default=False)),
                ('departing_time', models.CharField(choices=[('6.00 AM', '6.00 AM'), ('8.00 AM', '8.00 AM'), ('10.00 AM', '10.00 AM'), ('12.00 PM', '12.00 AM'), ('3.00 PM', '3.00 PM'), ('4.00 PM', '4.00 PM'), ('6.00 PM', '6.00 PM'), ('8.00 PM', '8.00 PM'), ('10.00 PM', '10.00 PM')], max_length=8)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.Routes')),
            ],
        ),
        migrations.AddField(
            model_name='travelling',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.Vehicle'),
        ),
        migrations.AddField(
            model_name='parcelfee',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.Routes'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.Routes'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.Passager'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matatu.Vehicle'),
        ),
    ]
