# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0003_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
