# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0004_booking_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
