# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0005_booking_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_paid',
            field=models.FloatField(),
        ),
    ]
