# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatu', '0006_auto_20161211_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=32),
        ),
    ]
